### ISSUE TITLE
How to set the maximum number of stars

### ISSUE THREAD

**Issue by nericode** [triniwiz/nativescript-star-ratings#9]
### Make sure to check the demo app(s) for sample usage 
check
### Make sure to check the existing issues in this repository 
ckeck
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
- iOS/Android/Both 
### Please, provide the following version numbers that your issue occurs with:

- CLI: 3.4.3
- Cross-platform modules: {
  "description": "Application private",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "mx.com.waisoft.appcustomerappli",
    "tns-android": {
      "version": "3.4.2"
    }
  },
  "dependencies": {
    "@angular/animations": "~5.2.0",
    "@angular/common": "~5.2.0",
    "@angular/compiler": "~5.2.0",
    "@angular/core": "~5.2.0",
    "@angular/forms": "~5.2.0",
    "@angular/http": "~5.2.0",
    "@angular/platform-browser": "~5.2.0",
    "@angular/platform-browser-dynamic": "~5.2.0",
    "@angular/router": "~5.2.0",
    "nativescript-angular": "~5.2.0",
    "nativescript-cardview": "^2.0.5",
    "nativescript-geolocation": "^4.2.5",
    "nativescript-google-maps-sdk": "^2.5.0",
    "nativescript-google-places-autocomplete": "^1.0.3",
    "nativescript-ng-shadow": "^2.1.0",
    "nativescript-star-ratings": "^1.0.0",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-autocomplete": "^3.6.0",
    "nativescript-ui-sidedrawer": "^3.5.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.5.2",
    "tns-core-modules": "~3.4.0",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~5.2.0",
    "@ngtools/webpack": "~1.9.4",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "copy-webpack-plugin": "~4.3.0",
    "css-loader": "~0.28.7",
    "extract-text-webpack-plugin": "~3.0.2",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "~0.6.0",
    "nativescript-dev-webpack": "^0.9.2",
    "nativescript-worker-loader": "~0.8.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.2.1",
    "typescript": "~2.6.2",
    "uglifyjs-webpack-plugin": "~1.1.6",
    "webpack": "~3.10.0",
    "webpack-bundle-analyzer": "^2.9.1",
    "webpack-sources": "~1.1.0"
  }
}

**Comment by Emmarex** [comment]
This would work
```<star:StarRating emptyBorderColor="#eeeeee" emptyColor="#eeeeee" filledColor="#00b8d4" value="2" max="5" isindicator="false" horizontalAlignment="center" verticalAlignment="center" />```


Take note of the ```horizontalAlignment="center"``` and ```max="5"```

**Comment by erwol** [comment]
Thanks @Emmarex. Do you how any idea about why horizontal and vertical alignment are required here?
